### ISSUE TITLE
responsebody检测没用吗

### ISSUE THREAD

**Issue by h3ak** [graynjo/Heimdallr#12]
{
        rulename: "f66_thinkphp_cms_responsebody_3",
        type: 2,
        commandments:"ThinkPHP: 响应体包含ThinkPHP v5报错banner特征",
        ruleposition: 5,
        rulecontent: /十年磨一剑 \- 为API开发设计的高性能框架/im
    },这种responsebody型的规则匹配貌似都没用

**Comment by h3ak** [comment]
![image](https://github.com/Ghr07h/Heimdallr/assets/111056070/73e279dd-0ac8-4b76-9118-a97fee1811ca)
自己编写了几条responsebody规则 貌似也不行

**Comment by h3ak** [comment]
![image](https://github.com/Ghr07h/Heimdallr/assets/111056070/e94978c9-e09f-41b0-8440-79d641ffdd6c)
自己编写了几条responsebody的规则貌似也不行

**Comment by Ghr07h** [comment]
![image](https://github.com/Ghr07h/Heimdallr/assets/49585390/35410ea0-6b8d-4085-bbea-a89b478674dc)

**Comment by h3ak** [comment]
![image](https://github.com/Ghr07h/Heimdallr/assets/111056070/d65ce251-b3ff-4458-b124-7d52ef25876b)
是开启的zh状态qwq

**Comment by h3ak** [comment]
![Uploading image.png…]()
请问我这样设置规则为什么检测不到呀qwq

**Comment by h3ak** [comment]
请问我这样设置规则为什么检测不到呀qwq
![image](https://github.com/Ghr07h/Heimdallr/assets/111056070/372efde3-21b1-4d8a-b1fe-9dd8a9b918cc)
