### ISSUE TITLE
Thanks a lot

### ISSUE THREAD

**Issue by Pass-A** [graynjo/Heimdallr#8]
希望可以添加响应流量自定义敏感字符匹配功能，特别是前端JS的可能存在很多可利用的信息，可以把JS的匹配范围交给使用者

**Comment by Ghr07h** [comment]
自定义的正则表达式编写错误可能产生大量回溯导致浏览器性能降低，甚至有触发XSS的风险（虽然Chrome Mainfest 3 存在一定沙箱和禁止非信任源js运行的机制）。简单的字符匹配建议使用浏览器调试工具的源代码模块的文件夹搜索功能，或者使用JS敏感信息收集工具来批量筛选可用信息。如果一些特定目标确实需要自定义规则，你可以按照README的继续开发-二次开发-指纹模块的指引来自定义一些规则，或者直接在issue中提交通用规则，我会在验证可用性后添加到新版本中。
![image](https://user-images.githubusercontent.com/49585390/216917793-a47839e9-e69f-4506-b250-f4e11940de7e.png)
